services:

  reverseproxy:
    image: reverseproxy
    container_name: reverse-proxy
    build:
      context: ./server
    ports: 
      - 8080:8080
    restart: always

  server:
    depends_on:
      - reverseproxy
    image: generate
    container_name: generate
    build: 
      context: ./generate
    restart: always