services:

  reverseproxy:
    image: reverseproxy
    container_name: reverse-proxy
    build:
      context: ./reverseproxy
    ports: 
      - 8080:8080
    restart: always

  generate:
    depends_on:
      - reverseproxy
    image: generate
    container_name: generate
    env_file:
      - .env
    build: 
      context: ./generate
    restart: always

  client:  
    depends_on:
      - reverseproxy
    image: client
    env_file:
      - .env
    container_name: client
    build:
      context: ./client
    restart: always